### ISSUE TITLE
how to get the dataset that you used?

### ISSUE THREAD

**Issue by KingMV** [Shiv-Kumar-Yadav9/Classroom-Event-Detection#1]
Thanks for your work about human action recognition, this is a good demo for new babes! When I review your code, I can not find the dataset folder and evaluate codes file for calculating the precision.  can you provide these files?

**Comment by YAwei666** [comment]
I also want to know about the type of dataset.

**Comment by Shiv-Kumar-Yadav9** [comment]
The dataset was recorded by the college and hence cannot be shared. The type of dataset is video sequences of more then 15 seconds. You will need at least 10 videos in each category to get the minimum satisfactory results. The frames are selected after dropping 5 next frames. In end each set of 10 frames form the input for the 3DCNN network.
