### ISSUE TITLE
how can I train the dataset of myself?

### ISSUE THREAD

**Issue by YAwei666** [Shiv-Kumar-Yadav9/Classroom-Event-Detection#2]
thank you for your sharing, it is really good for me, and I want to know how can I train the dataset using my dataset? thank you for your reply

**Comment by Shiv-Kumar-Yadav9** [comment]
You need to follow the directory structure provided in Github and just place the corresponding files in their respective directories. The jupyter notebook reads the directories accordingly. Make sure you set the current working directory.
