### ISSUE TITLE
the use of MEEMTracker

### ISSUE THREAD

**Issue by JayjieL** [Shiv-Kumar-Yadav9/Classroom-Event-Detection#3]
Thanks for your work.
I have some questions here.I encountered some mistakes when used MEEMTracker.
Some necessary matlab code is missing in this repo. i found some here[https://github.com/JHvisionchen/MEEM-matlab](url), but still can't run well.
so, could you please make a supplement～

**Comment by Shiv-Kumar-Yadav9** [comment]
The code requires all the files that they have in their official website. So you must download all the files and then just replace the file MEEMTracker.m with the file uploaded in the Event-detection-in-classroom repository.

**Comment by hithendra-l** [comment]
Thank you for your work.
I want to know if you can use octave instead of matlab and if so what are the changes that has to be made?
